config/routes.rb
Rails.application.routes.draw do

  resources :banners

  root 'page#index'

  post '/newsletters/create' => 'newsletters#create'

  get '/contato' => 'page#contato'
  post '/contato' => 'page#post_contato'

  scope '/admin' do
    get '/' => 'sessions#new'
    get '/cadastro' => 'users#new', as: :register
    post '/cadastro' => 'users#create', as: :post_register
    resources :cakes
    resources :categories
    resources :clippings
    resources :notices
    resources :stores
  end

  scope '/page' do
    get '/novidades' => 'page#novidades'
    get '/imprensa' => 'page#imprensa'
    get '/onde-encontrar' => 'page#onde_encontrar'
    get '/imprensa' => 'page#imprensa'
    get '/nossos-bolos' => 'page#nossos-bolos'
  end
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

app/models/banner.rb
class Banner < ActiveRecord::Base
end

app/models/cake.rb
class Cake < ActiveRecord::Base
  belongs_to :category

  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates :photo, attachment_presence: true
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

  validates_presence_of :name, :content, :nutrition_content, :recipe, :category_id, :message => "é um campo obrigatório"
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :cakes
  # Create slugs
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  #You don't necessarily need this bit, but I have it in there anyways
  def should_generate_new_friendly_id?
   slug.nil? || name_changed?
  end
  # Validating Images
  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates :photo, attachment_presence: true
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

  validates :name, :excerpt, presence: true
end

app/models/city.rb
class City < ActiveRecord::Base
end

app/models/clipping.rb
class Clipping < ActiveRecord::Base
  # Create slugs
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  #You don't necessarily need this bit, but I have it in there anyways
  def should_generate_new_friendly_id?
   slug.nil? || title_changed?
  end
  # Validating Images
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates :avatar, attachment_presence: true
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  validates :title, :content, presence: true
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates_presence_of :name, :email, :subject, :msg, :message => "é um campo obrigatório"
  validates_format_of :email, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/, :message => "esta com formato inválido"

end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
  validates :name, :email, presence: true
  validates :email,  uniqueness: true
end

app/models/notice.rb
class Notice < ActiveRecord::Base
end

app/models/store.rb
class Store < ActiveRecord::Base
  geocoded_by :address, :latitude  => :lat, :longitude => :lng
  after_validation :geocode

  def address
    [:address, :num, :district].compact.join(', ')
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :name, :email, :password_confirmation, presence: true
  validates :email,  uniqueness: true
  validates :password, confirmation: true

  def is_admin?
    self.role == "admin"
  end

end

app/controllers/page_controller.rb
class PageController < ApplicationController
	def index

	end
	def novidades
	  #code
	end
	def imprensa
		#code
	end
	def onde_encontrar
		#code
	end
	def contato
		@message = Message.new
	end
	def post_contato
		@message = Message.new(message_params)
		if @message.valid?
			  MessageMailer.contact_message(params[:message]).deliver_later
				flash[:success] = "Mensagem enviada com sucesso"
				redirect_to contato_url
		else
			render :contato
		end
	end
	private
	def message_params
		params.require(:message).permit(:name, :subject, :email,:msg)
	end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  layout "admin", :except => [:show]
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to store_url, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :tel, :cel, :waths, :hour, :address, :num, :comp, :district, :lat, :lng, :city_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/helpers/cake_helper.rb
module CakeHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clippings_helper.rb
module ClippingsHelper
end

app/helpers/groselhas_helper.rb
module GroselhasHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/stores/_form.html.erb
<div class="row">
  <div class="col-md-6">
    <%= form_for(@store) do |f| %>
      <%= render "partials/notifications", object: @store %>
      <div class="alert alert-info"><%= flash[:success] %></div>
      <div class="form-group">
        <label for="name">Nome</label>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <label for="name">Telefone</label>
        <%= f.text_field :tel, class: "form-control" %>
      </div>
      <div class="form-group">
        <label for="name">Celular</label>
        <%= f.text_field :cel, class: "form-control" %>
      </div>
      <div class="form-group">
        <label for="name">Wathsapp</label>
        <%= f.text_field :waths, class: "form-control" %>
      </div>
      <div class="form-group">
        <label for="name">Horário de funcionamento</label>
        <%= f.text_field :hour, class: "form-control" %>
      </div>
      <div class="form-group">
        <label for="name">Endereço</label>
        <%= f.text_field :address, class: "form-control" %>
      </div>
      <div class="form-group">
        <label for="name">Número</label>
        <%= f.text_field :num, class: "form-control" %>
      </div>
      <div class="form-group">
        <label for="name">Complemento</label>
        <%= f.text_field :comp, class: "form-control" %>
      </div>
      <div class="form-group">
        <label for="name">Bairro</label>
        <%= f.text_field :district, class: "form-control" %>
      </div>
      <div class="form-group">
        <label for="name">Nome</label>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group text-right">
        <%= f.submit 'Enviar', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form' %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stores</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= link_to 'Show', store %></td>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Store', new_store_path %>

app/views/stores/new.html.erb
<h1>Nova loja</h1>

<%= render 'form' %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>