config/routes.rb
Rails.application.routes.draw do

  resources :banners

  root 'page#index'

  post '/newsletters/create' => 'newsletters#create'

  get '/contato' => 'page#contato'
  post '/contato' => 'page#post_contato'

  scope '/admin' do
    get '/' => 'sessions#new'
    get '/cadastro' => 'users#new', as: :register
    post '/cadastro' => 'users#create', as: :post_register
    resources :cakes
    resources :categories
    resources :clippings
    resources :notices
    resources :stores
  end

  scope '/page' do
    get '/novidades' => 'page#novidades'
    get '/imprensa' => 'page#imprensa'
    get '/onde-encontrar' => 'page#onde_encontrar'
    get '/imprensa' => 'page#imprensa'
    get '/nossos-bolos' => 'page#nossos-bolos'
  end
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

app/models/banner.rb
class Banner < ActiveRecord::Base
end

app/models/cake.rb
class Cake < ActiveRecord::Base
  belongs_to :category

  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates :photo, attachment_presence: true
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

  validates_presence_of :name, :content, :nutrition_content, :recipe, :category_id, :message => "é um campo obrigatório"
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :cakes
  # Create slugs
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  #You don't necessarily need this bit, but I have it in there anyways
  def should_generate_new_friendly_id?
   slug.nil? || name_changed?
  end
  # Validating Images
  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates :photo, attachment_presence: true
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

  validates :name, :excerpt, presence: true
end

app/models/city.rb
class City < ActiveRecord::Base
end

app/models/clipping.rb
class Clipping < ActiveRecord::Base
  # Create slugs
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  #You don't necessarily need this bit, but I have it in there anyways
  def should_generate_new_friendly_id?
   slug.nil? || title_changed?
  end
  # Validating Images
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates :avatar, attachment_presence: true
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  validates :title, :content, presence: true
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates_presence_of :name, :email, :subject, :msg, :message => "é um campo obrigatório"
  validates_format_of :email, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/, :message => "esta com formato inválido"

end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
  validates :name, :email, presence: true
  validates :email,  uniqueness: true
end

app/models/notice.rb
class Notice < ActiveRecord::Base
end

app/models/store.rb
class Store < ActiveRecord::Base
  geocoded_by :address, :latitude  => :lat, :longitude => :lng
  after_validation :geocode

  def address
    [:address, :num, :district].compact.join(', ')
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :name, :email, :password_confirmation, presence: true
  validates :email,  uniqueness: true
  validates :password, confirmation: true

  def is_admin?
    self.role == "admin"
  end

end

app/helpers/banners_helper.rb
module BannersHelper
end

app/helpers/cake_helper.rb
module CakeHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clippings_helper.rb
module ClippingsHelper
end

app/helpers/groselhas_helper.rb
module GroselhasHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/page/contato.html.erb
    <section>
        <div class="bg-feead1">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12">

                        <div class="panel panel-contato">
                            <div class="panel-body">
                                <%= form_for @message, url: {action: "contato"} do |f| %>
                                <%= render "partials/notifications", object: @message %>
                                <div class="alert alert-info"><%= flash[:success] %></div>
                                    <div class="row">
                                        <div class="col-sm-6">
                                            <div class="form-group form-group-icon">
                                                <span class="icon-img icon-user"></span>
                                                <%= f.text_field :name, class: 'form-control', placeholder: 'Digite seu nome*' %>
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="form-group form-group-icon">
                                                <span class="icon-img icon-email"></span>

                                                <%= f.text_field :email, class: 'form-control', placeholder: 'Digite seu e-mail*' %>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-sm-12">
                                            <div class="form-group form-group-icon">
                                                <span class="icon-img icon-dialog"></span>

                                                <%= f.text_field :subject, class: 'form-control', placeholder: 'Assunto*' %>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-sm-12">
                                            <div class="form-group form-group-icon">
                                                <span class="icon-img icon-edit"></span>

                                                  <%= f.text_area :msg, class: 'form-control', placeholder: 'Digite sua mensagem*' %>

                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-sm-2 col-sm-push-10">
                                            <button type="submit" class="btn btn-danger btn-danger2 btn-block">Enviar</button>
                                        </div>
                                    </div>
                                <% end %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

app/views/page/imprensa.html.erb
<section class="banner" style="background-image: url(/assets/banner/banner-imprensa.png);">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h2>Imprensa</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing <br> elit. Nulla eu tristique neque.</p>
            </div>
        </div>
    </div>
</section>
<section class="form-box">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-sm-push-3">
                <div class="form-group">
                    <select class="selectpicker form-control">
                        <option selected disabled>Ordenar por</option>
                        <option>Opção 1</option>
                        <option>Opção 2</option>
                        <option>Opção 3</option>
                    </select>
                </div>
            </div>
        </div>
    </div>
</section>
<section>
    <div class="news">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="box-info">
                        <a href="#">
                            <div class="row">
                                <div class="col-sm-6">
                                    <img src="/assets/imprensa/imprensa_1.jpg" class="img-responsive">
                                </div>
                                <div class="col-sm-6 box-text">
                                    <div class="text">
                                        <p>POR STÉFANO SALLES - 14/08/2015</p>
                                        <p>Fundada há sete anos pela Vó Alzira, rede já está presente em oito estados</p>
                                        <p>RIO - Desempregada aos 60 anos, depois de enfrentar duas tragédias familiares, Alzira...</p>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="box-info">
                        <a href="#">
                            <div class="row">
                                <div class="col-sm-6">
                                    <img src="/assets/imprensa/imprensa_2.jpg" class="img-responsive">
                                </div>
                                <div class="col-sm-6 box-text">
                                    <div class="text">
                                        <p>POR ANDRÉA MACHADO 12/10/14</p>
                                        <p>Fábrica de Bolo Vó Alzira cresce, vira franquia e conquista todo o Estado do Rio</p>
                                        <p>Em setembro, um recorde: 73 mil bolos fabricados num único mês. Meta para dezembro...</p>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="box-info">
                        <a href="#">
                            <div class="row">
                                <div class="col-sm-6">
                                    <img src="/assets/imprensa/imprensa_3.jpg" class="img-responsive">
                                </div>
                                <div class="col-sm-6 box-text">
                                    <div class="text">
                                        <p>POR PRISCILA ZUINI COM RENNAN A. JULIO03 - 07/07/2015</p>
                                        <p>Empreendedora de 68 anos planeja levar franquia de bolos para os Estados Unidos</p>
                                        <p>Em 2007, durante o feriado de Páscoa, Alzira Ramos, aos 60 anos de idade, perdeu sua...</p>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="box-info">
                        <a href="#">
                            <div class="row">
                                <div class="col-sm-6">
                                    <img src="/assets/imprensa/imprensa_4.jpg" class="img-responsive">
                                </div>
                                <div class="col-sm-6 box-text">
                                    <div class="text">
                                        <p>POR ROBSON SALES</p>
                                        <p>Brasileiro adapta planos e investe em loja em Miami</p>
                                        <p>O dólar mais caro pode ter pesado no bolso dos empresários, mas não... </p>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="box-info">
                        <a href="#">
                            <div class="row">
                                <div class="col-sm-6">
                                    <img src="/assets/imprensa/imprensa_5.jpg" class="img-responsive">
                                </div>
                                <div class="col-sm-6 box-text">
                                    <div class="text">
                                        <p>SITE GUIA DO RIO</p>
                                        <p>Vai estar por aqui no natal?</p>
                                        <p>Edição especial de Natal na Fábrica de Bolo Vó Alzira - os bolos ganham ingredientes... </p>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="box-info">
                        <a href="#">
                            <div class="row">
                                <div class="col-sm-6">
                                    <img src="/assets/imprensa/imprensa_6.jpg" class="img-responsive">
                                </div>
                                <div class="col-sm-6 box-text">
                                    <div class="text">
                                        <p>POR RENNAN A. JULIO - 15/12/2015</p>
                                        <p>5 empreendedores brasileiros que fazem sucesso em Miami</p>
                                        <p>De acordo com o Ministério das Relações Exteriores, a Flórida é a região dos Estados Unidos...</p>
                                    </div>
                                </
                            </a>div>
                            </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6 col-sm-push-3">
                    <a href="#" class="btn btn-warning btn-block btn-lg">Ver mais</a>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/partials/_footer.html.erb
<footer>
    <div>
        <div class="container">
            <div class="row">
                <div class="col-sm-12">

                    <%= form_tag '/newsletters/create', remote: true, class: 'form-inline form-search', id: 'form_news' do  %>
                        <input type="hidden" name="newsletter[active]" value="1">
                        <label data-scroll-reveal="enter left and move 20px over 1s">
                            <img src="<%= image_path('footer/email.png') %>" class="img-responsive pull-left" data-scroll-reveal="enter left and move 40px over 1s">
                            <span>Fique por dentro das novidades</span>
                        </label>
                        <div class="input-group name" data-scroll-reveal="enter">
                            <input name="newsletter[name]" id="name_news" type="text" class="form-control" placeholder="Nome">
                        </div>
                        <div class="input-group email" data-scroll-reveal="enter">
                            <input name="newsletter[email]" id="email_news" type="text" class="form-control" placeholder="E-mail">
                            <span class="input-group-btn">
                              <button class="btn news_create transition" type="button">Enviar</button>
                            </span>
                        </div>
                      <% end %>
                      <p class="alert text-center alert-warning" style="display:none;" id="res"></p>
                </div>
            </div>
        </div>
    </div>
    <div>
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <span>2016 © Fábrica de Bolo - Todos os direitos reservados</span>
                    <a href="http://dizain.com.br/" target="_blank" class="transition">Desenvolvido por Diz’ain</a>
                </div>
            </div>
        </div>
    </div>
</footer>

app/views/partials/_header.html.erb
<header>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="navbar-top">
            <div class="navbar-top-text">
                <div class="navbar-top-bg transition"></div>
                <a href="#">Portal do franqueado</a>
            </div>
            <div class="container">
                <div class="nav-right">
                    <a href="#" target="_blank"><i class="icon icon-social-facebook-circle"></i></a>
                    <a href="#" target="_blank"><i class="icon icon-social-tumblr-circle"></i></a>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<%= root_path %>">
                    <img src="<%= image_path('header/logo-fabrica-de-bolo.png') %>" class="img-responsive">
                </a>
            </div>
            <div class="collapse navbar-collapse" id="navbar">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="onde-encontrar.html">Lojas</a></li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">nossos Bolos</a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="#">
                                    <img src="<%= image_path('bolos/tradicionais-thumb.jpg') %>">
                                    <div>
                                        <b>Tradicionais</b>
                                        <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at volutpat massa.</span>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <img src="<%= image_path('bolos/especiais-thumb.jpg') %>">
                                    <div>
                                        <b>Especiais</b>
                                        <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at volutpat massa.</span>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <img src="<%= image_path('bolos/diets-thumb.jpg') %>">
                                    <div>
                                        <b>Diets</b>
                                        <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at volutpat massa.</span>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <img src="<%= image_path('bolos/festa-thumb.jpg') %>">
                                    <div>
                                        <b>Festas</b>
                                        <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at volutpat massa.</span>
                                    </div>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li><a href="#">Novidades</a></li>
                    <li><a href="#">Imprensa</a></li>
                    <li><a href="<%= contato_path %>">Contato</a></li>
                    <li><a href="#">Seja um franqueado</a></li>
                </ul>
            </div>
        </div>
    </nav>
</header>

app/views/partials/_notifications.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <h2><%= pluralize(object.errors.count, "erro") %>:</h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/partials/admin/_footer.html.erb
<!--footer start-->
<footer class="site-footer">
    <div class="text-center">
        2016 - Dizain - Fabrica de Bolo
        <a href="blank.html#" class="go-top">
            <i class="fa fa-angle-up"></i>
        </a>
    </div>
</footer>
<!--footer end-->

app/views/partials/admin/_menu.html.erb
<!-- **********************************************************************************************************************************************************
MAIN SIDEBAR MENU
*********************************************************************************************************************************************************** -->
<!--sidebar start-->
<aside>
    <div id="sidebar"  class="nav-collapse ">
        <!-- sidebar menu start-->
        <ul class="sidebar-menu" id="nav-accordion">

            <p style="padding-top: 27px;" class="centered"><a href="profile.html"><i style="font-size:30px;" class="fa fa-user"></i></a></p>
            <h5 class="centered"><%= current_user.name %></h5>
            <li>
              <a href="<%= stores_path %>"><i class="fa fa-birthday-cake"></i> Lojas</a>
            </li>
            <li>
              <a href="<%= cakes_path %>"><i class="fa fa-birthday-cake"></i> Bolos</a>
            </li>

            <li>
              <a href="<%= categories_path %>"><i class="fa fa-tags"></i> Categorias</a>
            </li>
            <li>
              <a href="<%= banners_path %>"><i class="fa fa-tags"></i> Banners</a>
            </li>
            <li>
              <a href="<%= notices_path %>"><i class="fa fa-tv"></i> Novidades</a>
            </li>
            <li>
              <a href="<%= clippings_path %>"><i class="fa fa-tv"></i> Imprensa</a>
            </li>

        </ul>
        <!-- sidebar menu end-->
    </div>
</aside>
<!--sidebar end-->

app/views/partials/admin/_top.html.erb
<!-- **********************************************************************************************************************************************************
TOP BAR CONTENT & NOTIFICATIONS
*********************************************************************************************************************************************************** -->
<!--header start-->
<header class="header black-bg">
        <div class="sidebar-toggle-box">
            <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
        </div>
      <!--logo start-->
      <a href="<%= cakes_path %>" class="logo"><b><img src="<%= image_path('header/logo-fabrica-de-bolo.png') %>" alt="" /></b></a>
      <!--logo end-->
      <div class="nav notify-row" id="top_menu">
          <!--  notification start -->
        <%#    <ul class="nav top-menu">
              <!-- settings start -->
              <li class="dropdown">
                  <a data-toggle="dropdown" class="dropdown-toggle" href="index.html#">
                      <i class="fa fa-tasks"></i>
                      <span class="badge bg-theme">4</span>
                  </a>
                  <ul class="dropdown-menu extended tasks-bar">
                      <div class="notify-arrow notify-arrow-green"></div>
                      <li>
                          <p class="green">You have 4 pending tasks</p>
                      </li>
                      <li>
                          <a href="index.html#">
                              <div class="task-info">
                                  <div class="desc">DashGum Admin Panel</div>
                                  <div class="percent">40%</div>
                              </div>
                              <div class="progress progress-striped">
                                  <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                                      <span class="sr-only">40% Complete (success)</span>
                                  </div>
                              </div>
                          </a>
                      </li>
                      <li>
                          <a href="index.html#">
                              <div class="task-info">
                                  <div class="desc">Database Update</div>
                                  <div class="percent">60%</div>
                              </div>
                              <div class="progress progress-striped">
                                  <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                                      <span class="sr-only">60% Complete (warning)</span>
                                  </div>
                              </div>
                          </a>
                      </li>
                      <li>
                          <a href="index.html#">
                              <div class="task-info">
                                  <div class="desc">Product Development</div>
                                  <div class="percent">80%</div>
                              </div>
                              <div class="progress progress-striped">
                                  <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                                      <span class="sr-only">80% Complete</span>
                                  </div>
                              </div>
                          </a>
                      </li>
                      <li>
                          <a href="index.html#">
                              <div class="task-info">
                                  <div class="desc">Payments Sent</div>
                                  <div class="percent">70%</div>
                              </div>
                              <div class="progress progress-striped">
                                  <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width: 70%">
                                      <span class="sr-only">70% Complete (Important)</span>
                                  </div>
                              </div>
                          </a>
                      </li>
                      <li class="external">
                          <a href="#">See All Tasks</a>
                      </li>
                  </ul>
              </li>
              <!-- settings end -->
              <!-- inbox dropdown start-->
              <li id="header_inbox_bar" class="dropdown">
                  <a data-toggle="dropdown" class="dropdown-toggle" href="index.html#">
                      <i class="fa fa-envelope-o"></i>
                      <span class="badge bg-theme">5</span>
                  </a>
                  <ul class="dropdown-menu extended inbox">
                      <div class="notify-arrow notify-arrow-green"></div>
                      <li>
                          <p class="green">You have 5 new messages</p>
                      </li>
                      <li>
                          <a href="index.html#">
                              <span class="photo"><img alt="avatar" src="assets/img/ui-zac.jpg"></span>
                              <span class="subject">
                              <span class="from">Zac Snider</span>
                              <span class="time">Just now</span>
                              </span>
                              <span class="message">
                                  Hi mate, how is everything?
                              </span>
                          </a>
                      </li>
                      <li>
                          <a href="index.html#">
                              <span class="photo"><img alt="avatar" src="assets/img/ui-divya.jpg"></span>
                              <span class="subject">
                              <span class="from">Divya Manian</span>
                              <span class="time">40 mins.</span>
                              </span>
                              <span class="message">
                               Hi, I need your help with this.
                              </span>
                          </a>
                      </li>
                      <li>
                          <a href="index.html#">
                              <span class="photo"><img alt="avatar" src="assets/img/ui-danro.jpg"></span>
                              <span class="subject">
                              <span class="from">Dan Rogers</span>
                              <span class="time">2 hrs.</span>
                              </span>
                              <span class="message">
                                  Love your new Dashboard.
                              </span>
                          </a>
                      </li>
                      <li>
                          <a href="index.html#">
                              <span class="photo"><img alt="avatar" src="assets/img/ui-sherman.jpg"></span>
                              <span class="subject">
                              <span class="from">Dj Sherman</span>
                              <span class="time">4 hrs.</span>
                              </span>
                              <span class="message">
                                  Please, answer asap.
                              </span>
                          </a>
                      </li>
                      <li>
                          <a href="index.html#">See all messages</a>
                      </li>
                  </ul>
              </li>
              <!-- inbox dropdown end -->
          </ul> %>
          <!--  notification end -->
      </div>
      <div class="top-menu">
        <ul class="nav pull-right top-menu">
              <li><%= link_to "Log out", logout_path, method: "delete", class: "logout" %></li>
        </ul>
      </div>
  </header>
<!--header end-->