config/routes.rb
Rails.application.routes.draw do

  resources :banners

  root 'page#index'

  post '/newsletters/create' => 'newsletters#create'

  get '/contato' => 'page#contato'
  post '/contato' => 'page#post_contato'

  scope '/admin' do
    get '/' => 'sessions#new'
    get '/cadastro' => 'users#new', as: :register
    post '/cadastro' => 'users#create', as: :post_register
    resources :cakes
    resources :categories
    resources :clippings
    resources :notices
    resources :stores
  end

  scope '/page' do
    get '/novidades' => 'page#novidades'
    get '/imprensa' => 'page#imprensa'
    get '/onde-encontrar' => 'page#onde_encontrar'
    get '/imprensa' => 'page#imprensa'
    get '/nossos-bolos' => 'page#nossos-bolos'
  end
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

app/models/banner.rb
class Banner < ActiveRecord::Base
end

app/models/cake.rb
class Cake < ActiveRecord::Base
  belongs_to :category

  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates :photo, attachment_presence: true
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

  validates_presence_of :name, :content, :nutrition_content, :recipe, :category_id, :message => "é um campo obrigatório"
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :cakes
  # Create slugs
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  #You don't necessarily need this bit, but I have it in there anyways
  def should_generate_new_friendly_id?
   slug.nil? || name_changed?
  end
  # Validating Images
  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates :photo, attachment_presence: true
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

  validates :name, :excerpt, presence: true
end

app/models/city.rb
class City < ActiveRecord::Base
end

app/models/clipping.rb
class Clipping < ActiveRecord::Base
  # Create slugs
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  #You don't necessarily need this bit, but I have it in there anyways
  def should_generate_new_friendly_id?
   slug.nil? || title_changed?
  end
  # Validating Images
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates :avatar, attachment_presence: true
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  validates :title, :content, presence: true
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates_presence_of :name, :email, :subject, :msg, :message => "é um campo obrigatório"
  validates_format_of :email, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/, :message => "esta com formato inválido"

end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
  validates :name, :email, presence: true
  validates :email,  uniqueness: true
end

app/models/notice.rb
class Notice < ActiveRecord::Base
end

app/models/store.rb
class Store < ActiveRecord::Base
  geocoded_by :address, :latitude  => :lat, :longitude => :lng
  after_validation :geocode

  def address
    [:address, :num, :district].compact.join(', ')
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :name, :email, :password_confirmation, presence: true
  validates :email,  uniqueness: true
  validates :password, confirmation: true

  def is_admin?
    self.role == "admin"
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  layout "admin", :except => [:show]
  before_action :set_category, :only => [:edit, :update, :destroy]
  def index
    @categories = Category.order(id: :desc).page(params[:page]).per(2)
  end
  def show
    #code
  end
  def new
    @category = Category.new
  end
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Categoria criada com sucesso"
      redirect_to categories_url
    else
      render :new
    end
  end
  def edit
    # Edição de categoria
  end
  def update
    @category.update(category_params)
    if @category.save
      flash[:success] = "Categoria atualizada com sucesso"
      redirect_to edit_category_url(@category)
    else
      render :edit
    end
  end
  def destroy
    @category.delete
    flash[:success] = "Categoria deletada"
    redirect_to categories_url
  end

  private
  def set_category
    @category = Category.find(params[:id])
  end
  def category_params
    params.require(:category).permit(:name,:excerpt,:photo)
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
	def index

	end
	def novidades
	  #code
	end
	def imprensa
		#code
	end
	def onde_encontrar
		#code
	end
	def contato
		@message = Message.new
	end
	def post_contato
		@message = Message.new(message_params)
		if @message.valid?
			  MessageMailer.contact_message(params[:message]).deliver_later
				flash[:success] = "Mensagem enviada com sucesso"
				redirect_to contato_url
		else
			render :contato
		end
	end
	private
	def message_params
		params.require(:message).permit(:name, :subject, :email,:msg)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/helpers/cake_helper.rb
module CakeHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clippings_helper.rb
module ClippingsHelper
end

app/helpers/groselhas_helper.rb
module GroselhasHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<div class="row">
  <div class="col-md-6">
    <%= form_for @category,  :html => { :multipart => true, class: 'form' } do |f| %>
      <div class="alert alert-info"><%= flash[:success] %></div>
      <%= render "partials/notifications", object: @category %>
      <div class="form-group">
        <label for="name">Imagem</label>
        <%= image_tag @category.photo.url(:thumb) unless  @category.photo.url(:thumb).nil? %>
        <%= f.file_field :photo, class: "form-control" %>
      </div>
      <div class="form-group">
        <label for="name">Nome</label>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <label for="excerpt">Resumo</label>
        <%= f.text_area :excerpt, class: "form-control" %>
      </div>
      <div class="form-group text-right">
        <%= f.submit 'Enviar', class: 'btn btn-primary' %>
      </div>

    <% end %>
  </div>
</div>

app/views/categories/edit.html.erb
<h1>Editar categoria</h1>
<%= render 'form' %>

app/views/categories/index.html.erb
<h1>Categorias</h1>
<div class="alert alert-info"><%= flash[:success] %></div>
<div class="row">
  <div class="col-md-12">
    <a class="btn btn-primary" href="<%= new_category_path %>"><i class="fa fa-plus"></i> NOVA</a>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-md-12">
    <% if @categories.count > 0  %>
    <table class="table table-striped table-bordered">
      <tr>
        <th>Imagem</th>
        <th>Nome</th>
        <th>Editar</th>
        <th>Apagar</th>
      </tr>
      <% @categories.each do |c| %>
        <tr>
          <td><%= image_tag c.photo.url(:thumb) %></td>
          <td><%= c.name %></td>
          <td><a href="<%= edit_category_path(c.id) %>"><i class="fa fa-edit"></i></a></td>
          <td>
            <%= link_to c, method: :delete, data: {confirm: "Tem certeza?"} do %>
            <i class="fa fa-trash"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
    <div class="row">
      <div class="col-md-12 col-md-offset-5">
        <%= paginate @categories %>
      </div>
    </div>
    <% else %>
    <p class="alert alert-warning">Não há resultados</p>
    <% end %>

  </div>
</div>

app/views/categories/new.html.erb
<h1>Adicionar categoria</h1>
<%= render 'form' %>